name: Building a bundle from project
on: workflow_dispatch
jobs:
  building-bundle:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up GraalVM JDK 17
        run: |
          bash <(curl -sL https://get.graalvm.org/jdk)
          cd graalvm-*
          export JAVA_HOME=$(pwd)
          export PATH=$JAVA_HOME/bin:$PATH
          cd -
          ls
      - name: Build project
        run: mvn package -Pnative
      - name: Get release version
        run: echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Archive artifacts
        run: ls target -s
